"""Regenerate docs/CODE_MAP.md by parsing every Python file in the repository.

The map is generated from the AST rather than written by hand, so it cannot drift
out of sync with the code: every module, class and function in the repo appears,
with its signature, its one-line purpose, and where it is defined.

Run: python gen_codemap.py
"""
from __future__ import annotations

import ast
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "docs" / "CODE_MAP.md"

# Reading order: foundation first, then things built on it.
ORDER = [
    "twin.py", "generator.py", "features.py", "selfimprove.py", "leakage.py",
    "run.py", "make_report.py", "train_export.py", "bridge_selfcheck.py",
    "predict_on_video.py", "realdata_uci395.py", "pads_validation.py",
    "make_figures.py", "make_pgf.py", "probe_glb.py", "gen_codemap.py",
]

ROLE = {
    "twin.py": "Foundation. Forward-kinematics rig + tremor forward model.",
    "generator.py": "Dataset synthesis (coupled and decoupled label models).",
    "features.py": "Blind feature extraction from landmark trajectories.",
    "selfimprove.py": "The self-improving feature/model search and metrics.",
    "leakage.py": "Data-leakage audit suite.",
    "run.py": "Orchestrator: generate -> features -> search -> audit -> JSON.",
    "make_report.py": "Turns result JSON into RESULTS_REPORT.md and fills the paper notes.",
    "train_export.py": "Trains on all synthetic data and pickles the models.",
    "bridge_selfcheck.py": "Validates the saved-model inference path without MediaPipe.",
    "predict_on_video.py": "Sim-to-real bridge: real video -> MediaPipe -> prediction.",
    "realdata_uci395.py": "Real-tremor validation on UCI-395 pen trajectories.",
    "pads_validation.py": "Real-tremor validation on the PADS accelerometer cohort.",
    "make_figures.py": "Renders the paper figures as PDFs from the real model and data.",
    "make_pgf.py": "Emits the self-contained paper with figures as inline pgfplots.",
    "probe_glb.py": "One-off: inspects the rigged-hand asset (joints, skins, meshes).",
    "gen_codemap.py": "This file. Regenerates docs/CODE_MAP.md from the AST.",
}


def sig(node) -> str:
    a = node.args
    parts = [ar.arg for ar in a.posonlyargs + a.args]
    defaults = len(a.defaults)
    if defaults:
        for i in range(len(parts) - defaults, len(parts)):
            parts[i] += "=..."
    if a.vararg:
        parts.append("*" + a.vararg.arg)
    for ar in a.kwonlyargs:
        parts.append(ar.arg + "=...")
    if a.kwarg:
        parts.append("**" + a.kwarg.arg)
    return f"{node.name}({', '.join(parts)})"


def first_line(doc: str | None) -> str:
    if not doc:
        return ""
    for line in doc.strip().splitlines():
        if line.strip():
            return line.strip()
    return ""


def describe(path: Path) -> str:
    src = path.read_text(encoding="utf-8")
    tree = ast.parse(src)
    nloc = len(src.splitlines())
    out = [f"### `{path.name}`", ""]
    if path.name in ROLE:
        out += [f"**Role.** {ROLE[path.name]}", ""]
    out += [f"*{nloc} lines.* {first_line(ast.get_docstring(tree))}", ""]

    consts = [t.id for n in tree.body if isinstance(n, ast.Assign)
              for t in n.targets if isinstance(t, ast.Name) and t.id.isupper()]
    if consts:
        out += [f"Module constants: {', '.join('`%s`' % c for c in consts)}", ""]

    rows = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            rows.append((f"class `{node.name}`", first_line(ast.get_docstring(node)), node.lineno))
            for sub in node.body:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    rows.append((f"&nbsp;&nbsp;`{sig(sub)}`",
                                 first_line(ast.get_docstring(sub)), sub.lineno))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            rows.append((f"`{sig(node)}`", first_line(ast.get_docstring(node)), node.lineno))
    if rows:
        out += ["| Definition | Purpose | Line |", "|---|---|---|"]
        for name, doc, ln in rows:
            out.append(f"| {name} | {doc or '--'} | {ln} |")
        out.append("")
    return "\n".join(out)


def main():
    files = [f for f in ORDER if (HERE / f).exists()]
    files += sorted(p.name for p in HERE.glob("*.py") if p.name not in ORDER)
    body = ["# Code map",
            "",
            "Auto-generated by `gen_codemap.py` from the abstract syntax tree, so it",
            "always matches the code. Every module, class and function in the",
            "repository is listed below, in dependency order (foundation first).",
            "",
            "Regenerate with:",
            "",
            "```bash",
            "python gen_codemap.py",
            "```",
            "",
            "## Dependency order",
            "",
            "```",
            "twin.py            (no internal deps)",
            "  -> generator.py  (imports twin)",
            "  -> features.py   (imports twin)",
            "       -> selfimprove.py, leakage.py   (pure sklearn/numpy)",
            "            -> run.py            (imports generator, features, selfimprove, leakage)",
            "            -> train_export.py   (imports generator, features, twin)",
            "                 -> bridge_selfcheck.py, predict_on_video.py",
            "       -> realdata_uci395.py, pads_validation.py  (import features only)",
            "       -> make_figures.py, make_pgf.py            (import everything, read-only)",
            "```",
            ""]
    total = 0
    for name in files:
        p = HERE / name
        total += len(p.read_text(encoding="utf-8").splitlines())
        body.append(describe(p))
    body.insert(5, f"\nTotal: {len(files)} Python files, {total} lines of Python.")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(body), encoding="utf-8")
    print(f"wrote {OUT} ({len(files)} files, {total} lines)")


if __name__ == "__main__":
    main()
